### ISSUE TITLE
Publication on pypi

### ISSUE THREAD

**Issue by phainom** [INWTlab/dbrequests#2]
The package should be published on Pypi. The License File https://github.com/INWTlab/pydbtools/blob/master/LICENSE has to be updated and a publication handler should be added to setup.py.

**Comment by phainom** [comment]
https://pypi.org/project/pydbtools/

There is a (quite new) package on Pypi called pydbtools as well. Therefore, I would suggest to fork the package to a different repo, rename it (eg inwt-pydbtools or something like dbrequests) and publish it under that name. To avoid any impact on existing projects depending on pydbtools, further development may be still done here, which may be seen as the development 'branch' for the project. Alternatively, one could decide to refrain from publishing on Pypi and simply continue using github as a distribution platform as well as private pypi servers for the project.

Any opinions on this @amitghosh-inwt @marinarunge @aneudecker ?

**Comment by amitghosh-inwt** [comment]
I think we should avoid a naming conflict – no matter if the package will be available on Pypi later or not. Therefore, I suggest renaming the package. I would prefer a name that focuses on the features offered by the package without pre- or suffix *inwt*.

**Comment by amitghosh-inwt** [comment]
The repository has been renamed from pydbtools to [dbrequests](https://github.com/INWTlab/dbrequests).

**Comment by phainom** [comment]
The package is renamed and published to pypi.
https://pypi.org/project/dbrequests/

The package may be installed by running

```
pip install dbrequests
```

The travis job is not set up for continuous deployment yet. The uploading to pypi has to be done manually via twine. The setup.py publish command is still set up for the internal pypi server within INWT and should work fine. To upload to internal servers run 

```
python3 setup.py publish
```
with the information on the internal server stored only locally in .pypirc.
