### ISSUE TITLE
Bug: Unused arguments in __init__ of database class

### ISSUE THREAD

**Issue by wahani** [INWTlab/dbrequests#26]
The method definition of the init method of the dbrequests.Databse class allows the user to provide the arguments `escape_percentage` and `remove_comments`. Both arguments are not used throughout the class. 

```
def __init__(self, db_url=None, creds=None, sql_dir=None, connection_class=DefaultConnection,
                 escape_percentage=False, remove_comments=False, **kwargs):
```

To use the features associated to those arguments you have to supply them to the send_query method. 

- It makes sense to leave these arguments in the signature of send_query and
- remove them from the init method and keep the signature of init minimal.

@phainom any objections?

**Comment by phainom** [comment]
The purpose of including it into __init__ was to be able to set a default value for this at db creation. I would like to recover that functionality, by adding it properly to send_query (so the bug is not in __init__, its in send_query).

**Comment by wahani** [comment]
> The purpose of including it into init was to be able to set a default value for this at db creation. I would like to recover that functionality, by adding it properly to send_query (so the bug is not in init, its in send_query).

This would mean the arguments to the init method override the default values of the send_query method. This may lead to some confusion and apparently the feature has not been in use thus far. So I saw the chance to strip it from the interface: in the spirit of YAGNI.

**Comment by phainom** [comment]
I would assume if a user explicitly sets the value at initialization, they know what they do. I don't like passing that argument every time I need to send a query containing special characters, so I personally would prefer having the option to override it.

**Comment by wahani** [comment]
I think my analysis was wrong. It seems that these parameters are used here: https://github.com/INWTlab/dbrequests/blob/c4a37c864242509dbb59ce9235f2aca6e672a6d8/dbrequests/database.py#L84

All good then. Sorry for the confusion.

**Comment by phainom** [comment]
You're right, but still, if its that hard to decypher, its probably a bad implementation and does not follow [PEP 20](https://www.python.org/dev/peps/pep-0020/).
