### ISSUE TITLE
update-diffs not working with temporal tables

### ISSUE THREAD

**Issue by Cattes** [INWTlab/dbrequests#42]
The update-diffs method is not working with temporal tables, because it uses the `create temporary table like table_that_is_temporal ` syntax, which is not supported by maria db. 

Since `create table like table_that_is_temporal`is working, this is assumed to be a bug on the Database side.

We will have to find a workaround for that.

**Comment by wahani** [comment]
resolved by #43 (system versioned tables) and #44 (with partitions)
